import 'package:fmlfantasy/ui/views/my_cric3pick/models/my_crick3_model.dart';
import 'package:get/get_state_manager/src/simple/get_controllers.dart';

class MyCric3pickController extends GetxController {
  final List<MatchResult> matchResults = [
    MatchResult(
      tournamentName: "Indian Premier League",
      matchDateTime: DateTime(2025, 6, 20, 9, 0),
      earnings: 15,
      teamA: "Kolkata Knight Riders",
      teamB: "Punjab Kings",
      winner: "Kolkata Knight Riders",
      isWinner: true,
      winningCombination: [
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Batsman",
            "1", "Shubman Gill"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "2", "Sunil Narine"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "3", "Andre Russell"),
      ],
      yourCric3Picks: [
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Batsman",
            "1", "Shubman Gill"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "5", "Varun Chakravarthy"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "6", "Venkatesh Iyer"),
      ],
    ),
    MatchResult(
      tournamentName: "Indian Premier League",
      matchDateTime: DateTime(2025, 6, 22, 7, 30),
      earnings: 0,
      teamA: "Mumbai Indians",
      teamB: "Chennai Super Kings",
      winner: "Chennai Super Kings",
      isWinner: false,
      winningCombination: [
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Batsman",
            "1", "Ruturaj Gaikwad"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "2", "Deepak Chahar"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "3", "Ravindra Jadeja"),
      ],
      yourCric3Picks: [
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Batsman",
            "4", "Rohit Sharma"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "5", "Jasprit Bumrah"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "6", "Hardik Pandya"),
      ],
    ),
    MatchResult(
      tournamentName: "Indian Premier League",
      matchDateTime: DateTime(2025, 6, 25, 8, 0),
      earnings: 20,
      teamA: "Delhi Capitals",
      teamB: "Royal Challengers Bangalore",
      winner: "Royal Challengers Bangalore",
      isWinner: true,
      winningCombination: [
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Batsman",
            "1", "Virat Kohli"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "2", "Mohammed Siraj"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "3", "Glenn Maxwell"),
      ],
      yourCric3Picks: [
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Batsman",
            "4", "David Warner"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "5", "Anrich Nortje"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "6", "Axar Patel"),
      ],
    ),
    MatchResult(
      tournamentName: "Indian Premier League",
      matchDateTime: DateTime(2025, 6, 28, 6, 45),
      earnings: 0,
      teamA: "Sunrisers Hyderabad",
      teamB: "Lucknow Super Giants",
      winner: "Sunrisers Hyderabad",
      isWinner: false,
      winningCombination: [
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Batsman",
            "1", "Abhishek Sharma"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "2", "Bhuvneshwar Kumar"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "3", "Aiden Markram"),
      ],
      yourCric3Picks: [
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Batsman",
            "4", "KL Rahul"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "5", "Mark Wood"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "6", "Marcus Stoinis"),
      ],
    ),
    MatchResult(
      tournamentName: "Indian Premier League",
      matchDateTime: DateTime(2025, 7, 1, 9, 15),
      earnings: 50,
      teamA: "Rajasthan Royals",
      teamB: "Gujarat Titans",
      winner: "Rajasthan Royals",
      isWinner: true,
      winningCombination: [
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Batsman",
            "1", "Sanju Samson"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "2", "Trent Boult"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "3", "Riyan Parag"),
      ],
      yourCric3Picks: [
        DummyPlayers("hassets/new_images/headshot_placeholder.png", "Batsman",
            "4", "Shubman Gill"),
        DummyPlayers("assets/new_images/headshot_placeholder.png", "Bowler",
            "5", "Rashid Khan"),
        DummyPlayers("assets/new_images/headshot_placeholder.png",
            "All-rounder", "6", "Hardik Pandya"),
      ],
    ),
  ];
}
